dsocial118/SISOC

Legajos/templates/Legajos/legajosdimensiones_form.html, static/custom/css/utils.css, static/custom/js/legajosdimensionesform.js, templates/includes/base.html
Creada funcionalidad para filtrar en frontend preguntas vinculadas a educación.
=> Dev victoria10 6

Legajos/forms.py, Legajos/models.py, Legajos/templates/Legajos/legajogrupohogar_form.html, Legajos/templates/Legajos/legajos_detail.html, Legajos/urls.py, Legajos/views.py, config/settings.py
Se implementa la funcionalidad de grupo hogar en el apartado del legajo, tanto el conteo de personas como la asignacion, modificacion y eliminacion al grupo hogar
=> ✨Feature : Legajo - Grupo Hogar

Legajos/views.py
- Se soluciono el error 404 que habia en `legajos/dimensiones/editar/<pk>` por la vista DimensionesUpdateView en Legajos. Imagen adjunta
- Se agrego un FIXME para recordar optimizacion en Legajos views
=> Fix error 404 en DimensionesUpdateView

Usuarios/middleware.py, Usuarios/urls.py, Usuarios/views.py
[Tarea en Notion](https://www.notion.so/Error-en-logout-afc403a55d9e4202ac4eca1cd00f560e)
Solucion: Migracion de logout view innecesaria a la nativa de Django 
Informacion adicional: Seria interesante revisar mas vistas que puedan ser reemplazadas por las nativas de django
- Se elimino la view custom de logout
- Se implmeento la vista nativa de logout
- Se agrego un #FIXME para recordar la revision del middleware de login (ya que va a producir un error similar al solucionado en esta tarea
Automatico:
Manual: Logearse y deslogearse. Si no hay error, esta funcionando
=> DES-24 Error en logout

Legajos/models.py
- **Tarea:** https://www.notion.so/2d45a07dba2844d58f4eeb7a178c22b8?v=091b5c62f438468b84bd2cc14fd5bac2&p=db82c6d8a26d492ca393f3263d0ab412&pm=c
Se agrego una excepcion que valida que sea positivo
- Lista detallada de los cambios realizados en el código y el porque en caso de ser necesario.
- Instrucciones específicas sobre como testear el cambio y cual es el comportamiento esperado .
- Cualquier captura de pantalla que ayude a la review.
=> Se agrego una excepcion para que valide que el campo sea positivo

Legajos/templates/Legajos/legajosdimensiones_detail.html, Legajos/views.py
- **Tarea:** [[Enlace a Notion](URL_AQUI)](https://www.notion.so/Dimensiones-Salud-9b653d4ad3ff41cbb0531bb9c3999c1c)
Se agrego en template/legajosdimension_detail.html la secicon de salud
Se agrego en vies.py un .first() en la linea 247 para que traiga bien los datos al template
ninguna
Se agrego en template/legajosdimension_detail.html la secicon de salud
Se agrego en vies.py un .first() en la linea 247 para que traiga bien los datos al template
Entrar a un legajo cualquiera que tenga datos cargados de dimensionsalud y verificar que se vean los cambios echos
/legajos/ver/155118 …
=> DAD-116 Dimensiones  salud

Legajos/templates/Legajos/legajosdimensiones_detail.html, Legajos/templates/Legajos/legajosdimensiones_form.html
- **Tarea: DAD-118 Dimension Educacion** [Enlace a Notion](https://www.notion.so/Dimensiones-Educaci-n-cbf3b5bcb55f4cc1a3560def205a1fec)
- Depende de la branch DAD-106_Dimension_Vivienda en donde se corrigio los errores de compatibilidad con la db
- Se Acomodaron en el template los Establecimientos debajo de las provincias tal cual decia la tarea.
-
- Editar un legajo
- seleccionar una opcion de los siguientes desplegables "le interesa estudiar", "le interesa algun curso"
- ver que se guarde en la db y en la vista detalle.
-
=> Dad 118 dimension educacion

Legajos/templates/Legajos/legajosdimensiones_detail.html, Legajos/views.py
- **Tarea: Agregar a vista detalle las preguntas faltantes** [Enlace a Notion](https://www.notion.so/Dimensiones-Viviendas-Desplegable-99f3dbb0bb1542bf9f1add6410d18746)
- Se agrego a el template de legajosdimensiones_detail.html las preguntas faltantes sobre el desagüe, gas, techos, agua.
- Se agrego a la vista los fields_mapping_vivienda los modelos para que se guarden el la base de datos.
- 
- 
-
- Editar un legajo
- ir a vista detalle
- Ver que esten los cambios.
- Cualquier captura de pantalla que ayude a la review.
=> Detalles vivienda

Legajos/validation_middleware.py, config/settings.py
- **Tarea:** 
https://github.com/dsocial118/SISOC/issues/67
Se solicito que se agregen valdaciones de caracteres especiales para todos los campos, las ecepciones son estas -> './@-
Se implemento un middle ware que valide los campos
Se implemento un middle ware que valide los campos
Enviar un formulario cualquiera con los caraceteres especiales para ver si valida o no estos son los unicas ecepciones -> './@-
Tiene que mostar un cartel rojo …
=> Validacion para caracteres especiales

Legajos/templates/Legajos/legajogrupofamiliar_form.html
- **Tarea:** 
https://github.com/dsocial118/SISOC/issues/49
No se oculta la tabla para agregar un legajo cuando se busca
se agrego una clase para que se oculte cuando se encuentra una busqueda
se agrego una clase para que se oculte cuando se encuentra una busqueda
Buscar un legajo que no este asi aparace la tabla y despues buscar un que si este asi se oculta
ej buscar "asdasds" y despues buscar "perez"
- Cualquier captura de pantalla que …
=> cambios para que se visualice la tabla y se oculte cuando corresponde

Legajos/validation_middleware.py
https://github.com/dsocial118/SISOC/issues/67
- **Tarea:** 
validacion de campos de los formularios
se agrego a la validacion ()
se agrego a la validacion ()
- Instrucciones específicas sobre como testear el cambio y cual es el comportamiento esperado .
- Cualquier captura de pantalla que ayude a la review.
=> se agrego los () a las validaciones

static/custom/js/legajogrupohogarform.js
- **Tarea:** 
[se agrego lo mismo que en el otro pr para que se pueda ocultar y ver la tabla](https://github.com/dsocial118/SISOC/issues/49)
se agrego lo mismo que en el otro pr para que se pueda ocultar y ver la tabla
se agrego lo mismo que en el otro pr para que se pueda ocultar y ver la tabla
En grupo hogar ver si se muestra o no la tabla para agregar usuario cuando se hace una busqueda
=> fix en grupo hogar

static/custom/js/legajosform.js
(Recordar vincular el issue)
- Se recupero el js sobre provincias, municipios y localidades y se lo agrego al archivo `legajosform.js`
- Para probarlo que funcione es necesario tener la base de datos actualizada con las querys que paso nehui.
- 
- 
.github/pull_request_template.md
=> Agregado JS sobre la funcionalidad de las provincias, municipios y localidades

configuraciones/admin.py, legajos/admin.py, legajos/models.py
#109 
- Creacion de admins para modelos varios de configuraciones y legajos para que los funcionales puedan manejar las opciones.
- 
- Implementacion del admin.py en configuraciones y legajos
- 
.github/pull_request_template.md
=> #109 - Enriquecimiento de los admins

legajos/views.py
=> #104 - Añadi agua, desague y techos al update de la dimension vivienda

config/middlewares/no_special_characters.py
[(Recordar vincular el #issue)](https://github.com/dsocial118/SISOC/issues/108)
Se agergo el ° a los caracteres especiales
Se agergo el ° a los caracteres especiales
Entrar a un form y tratar de enviarlo con este caracter -> °
=> se agrego el caracter ° #108

config/urls.py, templates/includes/base.html, usuarios/templates/login.html, usuarios/templates/passwords/password_reset_complete.html, usuarios/templates/passwords/password_reset_confirm.html
=> #58 - Borrado de lo innecesario para la demo de legajo comedores

legajos/forms.py
No hay
Se cambio las validaciones de los formularios para que no sean requeridos los campos de prob,loc,muni
Se cambio las validaciones de los formularios para que no sean requeridos los campos de prob,loc,muni
Se cambio las validaciones de los formularios para que no sean requeridos los campos de prob,loc,muni
Cargar un formulario que no tenga los campos seleccionados de prob,loc,muni
=> cambios para que no sean requeridos

.djlintrc, legajos/templates/legajos/legajos_detail.html
=> Habilite mas lineas maximas en el html

legajos/templates/legajos/legajoalertas_form.html, legajos/templates/legajos/legajos_detail.html, legajos/templates/legajos/legajosdimensiones_form.html, legajos/views.py
https://github.com/dsocial118/SISOC/issues/140
Se modificaron las querys para que cuente las alertas y se modificaron un par de bugs que encontre por ahi
Se modifico la vista de detalles de legajs, la view de lagajos 
=> Alarmas  indicadores de riesgo #140

configuraciones/templates/Configuraciones/acciones_list.html, configuraciones/templates/Configuraciones/agentesexternos_list.html, configuraciones/templates/Configuraciones/alertas_list.html, configuraciones/templates/Configuraciones/categoriaalertas_list.html, configuraciones/templates/Configuraciones/equipos_list.html, configuraciones/templates/Configuraciones/gruposdestinatarios_list.html, configuraciones/templates/Configuraciones/indices_list.html, configuraciones/templates/Configuraciones/organismos_list.html, configuraciones/templates/Configuraciones/planessociales_list.html, configuraciones/templates/Configuraciones/programas_list.html, configuraciones/templates/Configuraciones/secretarias_list.html, configuraciones/templates/Configuraciones/subsecretarias_list.html, configuraciones/templates/Configuraciones/vacantes_list.html, legajos/templates/legajos/acciones_sociales.html, legajos/templates/legajos/indices.html, legajos/templates/legajos/intervenciones_salud.html, legajos/templates/legajos/legajos_list.html, legajos/templates/legajos/legajos_reportes.html, legajos/templates/legajos/legajosarchivos_list.html, legajos/templates/legajos/legajosderivaciones_historial.html, static/custom/js/custom.js, usuarios/templates/usuarios/usuarios_list.html
- Se aplico el columnDefs para la primer columna de cada una de las datatables. Se definio que la columna sea siempre visible y evitamos que se filtre.
- 
-Testear que en configuraciones, legajos y reportes y en donde se aplique el tabladt esten funcionando que la columna quede estatica.
-no
=> #40 Funcionalidad columnDefs Agregada a los datatables

docker/django/entrypoint_cicd.py, legajos/forms.py
- Actualizados los campos y etiquetas de DimensionViviendaForm para mayor claridad y coherencia en la vista del usuario
=> Actualizadas las labels en forms.py de legajos

docker/django/entrypoint_cicd.py, legajos/templates/legajos/legajos_detail.html, legajos/templates/legajos/legajosdimensiones_detail.html
- Actualizadas las plantillas legajos_detail.html y legajosdimensiones_detail.html para utilizar el filtro si,no en valores booleanos.
=> #171 error visualizacion

legajos/templates/legajos/intervencion_detail.html
- Actualizada la visualización de la ruta de navegación en la plantilla intervencion_detail para mostrar el nombre completo
=> #174 Intervenciones
